[package]
name = "tetsu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow      = "1.0.68"
clap        = { version = "4.0.32", features = [ "derive" ] }
config      = "0.13.3"
indicatif   = { version = "0.17.2", features = [ "rayon", "tokio" ] }
lazy_static = "1.4.0"
md4         = "0.10.2"
memmap      = "0.7.0"
rayon = "1.6.1"
serde       = { version = "1.0.151", features = [ "derive" ] }
sqlx        = { version = "0.6.2", features = [ "runtime-tokio-rustls", "sqlite" ] }
tokio       = { version = "1.23.0", features = ["rt-multi-thread", "macros"] }
toml        = "0.5.10"
