format_macro_bodies = false
overflow_delimited_expr = true
use_field_init_shorthand = true

imports_granularity = "Crate"
group_imports = "StdExternalCrate"

use_small_heuristics = "Off"
single_line_if_else_max_width = 50
struct_lit_width = 36
struct_variant_width = 42
chain_width = 60
